name: Sample-Pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Set up JDK 1.11
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '1.11'
        settings-path: "${{ github.workspace }}"
    - name: Run Gradle command
      shell: bash
      run: gradle
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: HTML Report
        path: "**/*"
